### ISSUE TITLE
no var name linked

### ISSUE THREAD

**Issue by diemort** [GASP-UFRGS/LHE-Proton-Writer#19]
https://github.com/GASP-UFRGS/LHE-Proton-Writer/blob/30e525309f771a40d45e4b1fe942d94c1fc798cf/Validation/root_plotter.py#L82

```
Traceback (most recent call last):
  File "/Users/diemort/Work/hep-ph/scalar-flux/root_plotter.py", line 82, in <module>
    eval(name).append(k.ReadObj())
    ^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'DDivmprotmmumu' is not defined
```

**Comment by Artur-UF** [comment]
New pr updates var names and with it corrects this issue

**Comment by diemort** [comment]
Traceback (most recent call last):
  File "/Users/diemort/Work/hep-ph/scalar-flux/root_plotter.py", line 247, in <module>
    DDlog[l][m].GetZaxis().SetTitle("d#sigma/d"+str(DDlog_xaxis[l])+"d"+str(DDlog_yaxis[l])+str(DDlog_varz[l]));
                                                                                                ^^^^^^^^^^
NameError: name 'DDlog_varz' is not defined. Did you mean: 'DDlog_varx'?
